name: Build

on:
  workflow_call:
    inputs:
      site_url:
        description: "Base URL for GitHub Pages"
        required: true
        type: string
      base_path:
        description: "Base path for GitHub Pages"
        required: false
        type: string
        default: ""
      upload_artifact:
        description: "Upload build artifact to GitHub Pages"
        required: false
        default: false
        type: boolean

env:
  ASTRO_TELEMETRY_DISABLED: 1
  DO_NOT_TRACK: 1
  HUSKY: 0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          node-version: 24
      - name: Restore Astro cache
        uses: actions/cache@v5
        with:
          path: .astro
          key: |
            ${{ runner.os }}-astro-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('src/**/*', 'astro.config.mjs') }}
          restore-keys: |
            ${{ runner.os }}-astro-${{ hashFiles('**/pnpm-lock.yaml') }}-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint check
        run: pnpm run lint
      - name: Format check
        run: pnpm run format:check
      - name: Build project
        env:
          SITE_URL: ${{ inputs.site_url }}
          BASE_PATH: ${{ inputs.base_path }}
        run: pnpm build
      - name: Upload Pages artifact
        if: inputs.upload_artifact == true
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist
